shop_store:
    resource: "@ShopStoreBundle/Resources/config/routing.yml"
    prefix:   /administrator/shop/

shop_site:
    resource: "@ShopSiteBundle/Resources/config/routing.yml"

shop_user:
    resource: "@ShopUserBundle/Resources/config/routing.yml"

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme
