parameters:
    shop_store.property.class: Shop\StoreBundle\Service\PropertyService
    shop_store.property.class: Shop\StoreBundle\Service\PropertyValuesService

services:
    shop_store.property:
        class: %shop_store.property.class%
        arguments: []

    shop_store.PropertyValues:
        class: %shop_store.property.class%
        arguments: []

